version: '3'
services:
  app:
    image: stock-tesouro-direto
    container_name: stock-tesouro-direto
    restart: always
    build:
      context: ./
      dockerfile: docker/Dockerfile
    environment:
      - CONTAINER_ROLE=app
    volumes:
      - ./:/var/www/
    ports:
      - 8090:80
    expose:
      - 8090
